### ISSUE TITLE
V25 商店企业微信更新支持treeland

### ISSUE THREAD

**Issue by winexw** [linuxdeepin/docs.deepin.io#11060]
### package information | 软件包信息

包名 | 版本
-- | --
com.qq.weixin.work.deepin |  4.1.31.6017deepin3

### Package repository address | 软件包仓库地址

https://winedata-dev.deepin.com/apps/com.qq.weixin.work.deepin/5f3c974/signed_com.qq.weixin.work.deepin_4.1.31.6017deepin3_amd64.deb

### changelog | 更新信息

最新版本企业微信，添加treeland支持

### test suggestion | 测试建议

1.  在V25上对企业微信核心功能冒烟测试

### Sphere of influence | 影响范围

只更新上架V25商店仓库

**Comment by Groveer** [comment]
[deb.tgz](https://github.com/user-attachments/files/18145639/deb.tgz)
treeland 安装包

**Comment by Groveer** [comment]
[deb.tgz](https://github.com/user-attachments/files/18145654/deb.tgz)
treeland 安装包  安装里面的包后才能正常运行wine程序

**Comment by babyfengfjx** [comment]
@vivianxf  可以手动安装上述两个安装包，验证企业微信基本功能，如验证通过，可以推进上架到25商店。

**Comment by vivianxf** [comment]
验证不通过，所有包安装成功后，treeland下启动企业微信失败
