### ISSUE TITLE
[Deepin Integration]~[V23-release]  v23 release loongarch64 iso update

### ISSUE THREAD

**Issue by Zeno-sole** [linuxdeepin/docs.deepin.io#11088]
### Package information | 软件包信息

包名 | 版本
--  | --
null

### Package repository address | 仓库地址

   https://ci.deepin.com/repo/deepin/deepin-ports/cdimage/20241223/

#### xxx (12.3.0-17deepin9) unstable; urgency=medium

  * move libgcc_s.so.1 to /usr for DEP17

**Comment by Zeno-sole** [comment]
**Integration Test Info**

解决loongarch64架构 iso  qemu安装失败、光盘刻录安装失败问题

### Test suggestion | 测试建议



### Influence | 影响范围
安装


### ADDITIONAL INFORMATION | 额外补充

**Comment by babyfengfjx** [comment]
@kobe337  请开展安装验证，确保安装、基本功能可用即可。

**Comment by kobe337** [comment]
【环境】：
镜像：https://ci.deepin.com/repo/deepin/deepin-ports/cdimage/20241223/

【结论】：
测试通过，暂无严重问题及影响, 覆盖场景：刻录u盘安装、qemu安装方式，验证通过，请研发同事确认，是否合入仓库。
![Image](https://github.com/user-attachments/assets/86dc49aa-b445-43d3-b16b-633fe61215f8)
![Image](https://github.com/user-attachments/assets/dbb2fc60-c50c-4acb-972c-63bf3946936f)
