### ISSUE TITLE
建议将右键菜单新建文档的固定四项去除

### ISSUE THREAD

**Issue by floatingrain** [linuxdeepin/docs.deepin.io#2346]
通过命令行搜索并且删除了/usr某目录下（忘了具体路径）新建办公文档等四个模板一共八个文件，然而发现右键菜单里依然停留老四项，通过浏览代码发现这四项是硬编码的，完全没有给用户自定义的空间。建议从代码中删除硬编码，改为类似扫描~/.Templete模板目录的形式，这样不失普通用户的易用性，也能满足高级用户自定义。顺便：模板都还是doc等二进制格式，这个也得改成新的docx等格式吧。

**Comment by meiyixiang** [comment]
41/5000 
This is good advice, but we need to think about how to provide developers with more convenient features like this.
