### ISSUE TITLE
[建议] 文档查看器,归档管理器,浏览器

### ISSUE THREAD

**Issue by LTreeshu** [linuxdeepin/docs.deepin.io#3119]
#1.文档查看器: 建议增加涂鸦功能
#2.浏览器:查看pdf时,建议增加涂鸦功能
#3.归档管理器: 在使用"提取"功能时,提示信息太小且不明显, 但提取的文件比较大时时间较长无法及时确认提取情况, 建议提取时间大于1s时增加提取进度窗口

**Comment by BLumia** [comment]
hi, 建议类反馈我这边帮您挪到讨论板，如果是 bug 再报到 issue 面板哦
