### ISSUE TITLE
[deepin v23 nightly]default-jdk : 依赖: openjdk-8-jdk 但无法安装它

### ISSUE THREAD

**Issue by gnuhub** [linuxdeepin/docs.deepin.io#3313]
### STEPS TO REPRODUCE | 复现步骤

```
sudo apt update -y
sudo apt install default-jdk -y

```

### OBSERVED RESULT | 观察到的结果

```
正在读取软件包列表... 完成
正在分析软件包的依赖关系树... 完成
正在读取状态信息... 完成
有一些软件包无法被安装。如果您用的是 unstable 发行版，这也许是
因为系统无法达到您要求的状态造成的。该版本中可能会有一些您需要的软件
包尚未被创建或是它们已被从新到(Incoming)目录移出。
下列信息可能会对解决问题有所帮助：

下列软件包有未满足的依赖关系：
 default-jdk : 依赖: openjdk-8-jdk 但无法安装它
E: 无法修正错误，因为您要求某些软件包保持现状，就是它们破坏了软件包间的依赖关系。
```

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

cat /etc/issue
Deepin GNU/Linux 23 Nightly \n \l

**Comment by Zeno-sole** [comment]
很抱歉，我们在计划发布新的版本，之后这个nightly版本不会在维护了。  可以安装openjdk-8-jdk看看报什么错误，看下具体是什么依赖挂掉了

**Comment by Zeno-sole** [comment]
查了下，debian 11以及之后的版本已不再提供openjdk8了，可以直接安装openjdk-11-jdk

**Comment by Zeno-sole** [comment]
> 

1. 不建议使用了，正式的v23仓库里面的基础库的版本比这个更新一些
2. 逐步脱离debian

**Comment by BLumia** [comment]
关于问题 2，如果有兴趣的话，可以从社区组团维护一个 debian stable 下可用的 DDE，有兴趣的话可以在单独的主题里一起讨论 :)

相关： https://github.com/linuxdeepin/developer-center/issues/3230 https://github.com/linuxdeepin/developer-center/discussions/3314
