### ISSUE TITLE
[dtkdeclarative] 编译错误--DDciIconPalette: 没有那个文件或目录(编译环境deepin v23 nightly )

### ISSUE THREAD

**Issue by gnuhub** [linuxdeepin/docs.deepin.io#3319]
### SUMMARY | 问题概要

在 v23 nightly 环境中尝试构建 dtkdeclarative 包，无法从源码构建成功。

### STEPS TO REPRODUCE | 复现步骤

``` shell
         sudo apt install build-essential devscripts debhelper -y
          sudo apt install -y qtdeclarative5-dev
          sudo apt install -y qtbase5-dev-tools
          sudo apt install -y qtquickcontrols2-5-dev
          sudo apt install -y libdtkgui-dev
          sudo apt install -y libdtkcore-dev
          sudo apt install -y qtdeclarative5-private-dev
          sudo apt install -y qtbase5-private-dev
          sudo apt install -y pkg-kde-tools 
          sudo apt install -y libgtest-dev
          debuild -b -uc -us
```

### OBSERVED RESULT | 观察到的结果

能够完成构建

### EXPECTED RESULT | 期望的结果

```
dqmlglobalobject_p.h:30:10: fatal error: DDciIconPalette: 没有那个文件或目录
   30 | #include <DDciIconPalette>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [Makefile:1879：dqmlglobalobject.o] 错误 1
make[2]: *** 正在等待未完成的任务....

```

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

deepin v23 nightly

**Comment by BLumia** [comment]
目前建议在 dtkdeclarative 正式发布一个版本后再尝试这个项目，目前这个项目的 CI 构建都还跑不过。

顺便，也建议把 issue 模板填完整一些，不然目前的信息完全看不出来是在什么环境下，使用什么步骤尝试的构建。

**Comment by BLumia** [comment]
> 能否在README补充一下仓库介绍和状态

有计划补充，其它项目的 README 有的也有点问题。

--------------

顺便补充点内容：

- 由于 deepin 的项目是提供了 debian 目录的，所以装依赖其实可以在项目目录内 `sudo apt build-dep .` ，会直接根据 debian 目录描述的依赖进行依赖的安装
- 一般如果不是开发，而是移植目的的话，其实建议获取对应 tag 使用的版本而不是 git master
