### ISSUE TITLE
【Deepin V23 Alpha2】文档工具链存在BUG，导致部分项目无法构建

### ISSUE THREAD

**Issue by wzyforgit** [linuxdeepin/docs.deepin.io#3909]
### SOFTWARE/OS VERSIONS | 软件/系统版本信息

系统：Deepin V23 Alpha2
架构：x86-64

### STEPS TO REPRODUCE | 复现步骤

1.拉取deepin-community下的ncnn、opencv-mobile，拉取linuxdeepin下的dtkmultimedia
2.使用apt解决构建依赖并使用dpkg-buildpackage命令构建ncnn和opencv-mobile，并安装其本体和dev包
3.使用apt解决构建依赖并使用dpkg-buildpackage命令构建dtkmultimedia

### OBSERVED RESULT | 观察到的结果

1.在make install阶段提示找不到qch文件，经过搜索发现是因为没有安装graphviz和qt5-default，此时补充安装这两个包，然后再重新构建
2.重新构建后依然在make install阶段提示找不到qch文件，通过查看构建日志发现报告index.qhp的XML标记存在问题（开始标记和结束标记不匹配），导致后续工具无法通过qhp文件生成qch文件
3.使用vscode打开构建目录下出错的index.qhp，发现标签确实是乱的

### EXPECTED RESULT | 期望的结果

能够像V20那样一次构建成功

**Comment by Zeno-sole** [comment]
@wzyforgit  文档工具指的的graphviz ？

**Comment by wzyforgit** [comment]
> @wzyforgit 文档工具指的的graphviz ？

明显是doxygen和qt的那个文档生成器啊

**Comment by BLumia** [comment]
可以随便贴一个失败的 CI 链接吗？还是说 CI 并不会失败，但本地构建会失败？

来自其他项目的可能相关的 PR： https://github.com/linuxdeepin/dtksystemsettings/pull/129 ，但不清楚 multimedia qch 生成失败的问题是否和这个相似。

**Comment by wzyforgit** [comment]
> 可以随便贴一个失败的 CI 链接吗？还是说 CI 并不会失败，但本地构建会失败？
> 
> 来自其他项目的可能相关的 PR： [linuxdeepin/dtksystemsettings#129](https://github.com/linuxdeepin/dtksystemsettings/pull/129) ，但不清楚 multimedia qch 生成失败的问题是否和这个相似。

1. GitHub CI那边只跑V20分支，没有跑V23分支
2. 目前已知V23本地构建会失败，内网打版本会失败
3. 另外已知dtkio可以构建成功，dtkdevice会构建失败，报错原因都是一样的
4. 今天按你给的这个链接继续排查

**Comment by wzyforgit** [comment]
就是因为内网打版本会失败，进而影响新版OCR集成至V23 beta，所以才提了这个issue =。=

**Comment by wzyforgit** [comment]
@BLumia @Zeno-sole @ArchieMeng 搞定了，虽然感觉有点玄学。。。[pr位置](https://github.com/linuxdeepin/dtkmultimedia/pull/44)
它这个新版的doxygen要求markdown的标题必须以单个井号开始，然后逐级递减，不能上来就搞两个井号的二级标题，不然生成的XML就是乱的 =。= 也不知道是feature还是bug

**Comment by BLumia** [comment]
果然是同一个问题啊 😂 

那就 close 掉了
