### ISSUE TITLE
文本编辑器未完美解决的问题

### ISSUE THREAD

**Issue by lizipeng0013** [linuxdeepin/docs.deepin.io#4044]
### SUMMARY | 问题概要

![1](https://user-images.githubusercontent.com/123794418/230894900-1e813c60-9e3c-45d7-a351-1f5539c5b3a6.gif)
![录屏_deepin-editor_20230410182107](https://user-images.githubusercontent.com/123794418/230898673-32c13511-b0ef-45f6-a13d-5eb23e57b21f.gif)

在这两个gif说明出现的错误

### SOFTWARE/OS VERSIONS | 软件/系统版本信息

系统版本：20.9（内测源更新）
软件版本：6.0.3

### STEPS TO REPRODUCE | 复现步骤

1.选中文字后拖动移动位置，撤销后再重做会出错
2.按回车键多次换行后，再选中文字按住Ctrl键拖动文本复制到多行，撤销正常，但撤销后再重做拖动复制的文本会都恢复到最后的同一行（前面拖动复制到了不同行）

**Comment by babyfengfjx** [comment]
@SuperEffie  请复现跟踪该问题。

**Comment by SuperEffie** [comment]
感谢您的反馈，给问题我们已经提交给研发同学进行定位修复，后期我们会持续跟踪该问题的~
关联bug单：https://pms.uniontech.com/bug-view-196349.html

**Comment by SuperEffie** [comment]
这个问题我们已经在内部建单跟踪，因为是v20.9的问题，可能更新会较慢。目前我们对v20.9相关的issue作关闭处理。若您后期在使用v23过程中遇到问题，也欢迎在github平台向我们反馈~
