### ISSUE TITLE
dde-dock: unknown type name 'WindowList'

### ISSUE THREAD

**Issue by dumabg** [linuxdeepin/docs.deepin.io#649]
I'm trying to compile dde-dock, but appears this error:

/home/mabg/dde-dock/frame/item/components/previewcontainer.h:53: error: unknown type name 'WindowList'; did you mean 'QWindowList'?
    void setWindowInfos(const WindowInfoMap &infos, const WindowList &allowClose);

**Comment by felixonmars** [comment]
You need to have devel files of dde-qt-dbus-factory installed.

**Comment by felixonmars** [comment]
You probably have an old version then.

**Comment by dumabg** [comment]
I've installed these ones:

libdframeworkdbus-dev/panda,now 1.0.4-1 amd64 [instalado]
  Qt DBus interface library for Deepin software (development files)

libdframeworkdbus2/panda,now 1.0.4-1 amd64 [instalado, automático]
  Qt DBus interface library for Deepin software (shared library)

**Comment by BLumia** [comment]
You can do a `apt build-dep dde-dock` first to make sure all package required to build is installed.

If you got the source via git (gerrit or github), try `apt policy dde-dock` to check which version of `dde-dock` you are using now, and do a `git checkout -b <tag version>` like `git checkout -b 4.7.3.3` for example, then you can build it. Another way to get a reproducible build is building the package with the source you get via `apt source dde-dock`.

FYI: building newer version of `dde-dock` also required newer version of dependencies installed ;)

**Comment by dumabg** [comment]
- sudo apt build-dep dde-dock: Nothing to update.
- apt policy dde-dock:
dde-dock:
  Instalados: 4.7.3.3-1
  Candidato:  4.7.3.3-1
  Tabla de versión:
 *** 4.7.3.3-1 1001
       1001 http://packages.deepin.com/deepin panda/main amd64 Packages
        100 /var/lib/dpkg/status

**Comment by hualet** [comment]
Then please tell us more about where did you get the source code and how you did the compilation specifically? @dumabg

**Comment by dumabg** [comment]
After upgrade to Deepin 5.18, it compiles.
